#!/bin/sh

# Update apt-get, zsh, ripgrep, fzf
brew update
brew upgrade
brew install ripgrep
brew install fzf
# Install zsh fzf completion
sh /usr/local/opt/fzf/install
brew install zsh zsh-completions
export SHELL="/bin/zsh"

# Copy files and init git
cd "$HOME/myconfig"
git submodule update --init --recursive
git pull --recurse-submodules=yes

# Install python packages
pip3 install -r requirements.txt

# Apply terminal configs
cd "dotfiles/.terminfo"
tic "tmux.terminfo"
tic "tmux-256color.terminfo"
tic "xterm-256color-italic.terminfo"

# Copy dotfiles to home directory
cd "$HOME/myconfig/dotfiles"
cp -rf * "$HOME"
cp -rf .[^.]* "$HOME"
cd "$HOME"

# Move the tmux ssh agent config in .ssh
mv "$HOME/myconfig/rc" "$HOME/.ssh/"

# Configure vimrc and YCM
cd "$HOME/.vim_runtime"
# Vim x11 capability
# sudo apt-get install vim-gtk -y

# Install vim config
sh install_awesome_vimrc.sh

# Tools to compile YCM
brew install cmake

cd "$HOME"

# Install tmux from source file
brew install tmux
tmux
tmux source-file "$HOME/.tmux.conf"
