#!/bin/sh

# Update apt-get, get zsh
yes | sudo apt-get update
yes | sudo apt-get upgrade
yes | sudo apt-get install zsh

# Copy files and init git
cd "$HOME/myconfig"
git submodule update --init --recursive
git pull --recurse-submodules=yes

cp -rf * "$HOME"
cp -rf .[^.]* "$HOME"
cd "$HOME"
rm -rf .git/
rm -rf .gitmodules
rm -rf scripts/

# Configure vimrc and YCM
cd "$HOME/.vim_runtime"
# Vim x11 capability
yes | sudo apt-get install vim-gtk
sh install_awesome_vimrc.sh

# Compile YCM
yes | sudo apt-get install build-essential cmake
yes | sudo apt-get install python-dev python3-dev
cd "sources_non_forked/YouCompleteMe/"
./install.py

cd "$HOME"

# Set default shell to zsh
# chsh -s "$(which zsh)"

# Install tmux from source file
sh tmux_build_from_source_ubuntu.sh
rm -rf tmux_build_from_source_ubuntu.sh
yes | sudo apt-get install xclip
yes | sudo apt-get install xsel
tmux source-file .tmux.conf
