#!/bin/sh

# Update apt-get, get zsh, ag, ack
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install zsh -y
sudo apt-get install ack-grep -y
sudo apt-get install silversearcher-ag -y
export SHELL="/bin/zsh"

# Install neovim
sudo add-apt-repository -y ppa:neovim-ppa/stable
sudo apt-get update && sudo apt-get install -y neovim
sudo pip3 install neovim

# Create config repo and symlink the .vimrc
mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
ln -s ~/.vim_runtime $XDG_CONFIG_HOME/nvim
ln -s ~/.vimrc $XDG_CONFIG_HOME/nvim/init.vim

# Copy files and init git
cd "$HOME/myconfig"
git submodule update --init --recursive
git pull --recurse-submodules=yes

cp -rf * "$HOME"
cp -rf .[^.]* "$HOME"
cd "$HOME"

# Move the tmux ssh agent config in .ssh
mv rc "$HOME/.ssh/"

# Remove extra files
rm -rf .git/
rm -rf .gitmodules
rm -rf scripts/

# Configure vimrc and YCM
cd "$HOME/.vim_runtime"
# Vim x11 capability
sudo apt-get install vim-gtk -y
sh install_awesome_vimrc.sh

# Compile YCM
sudo apt-get install build-essential cmake -y
sudo apt-get install python-dev python3-dev -y
cd "sources_non_forked/YouCompleteMe/"
python3 ./install.py

cd "$HOME"

# Install tmux from source file
sh tmux_build_from_source_ubuntu.sh
rm -rf tmux_build_from_source_ubuntu.sh
sudo apt-get install xclip -y
tmux
tmux source-file "$HOME/.tmux.conf"
